{
 "title": "Validator Monitoring Metrics",
 "description": "Provides information about Koii validator",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Validator Identity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vote Key",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "solana_validator_activated_stake",
     "legendFormat": "{{votekey}}"
    }
   ]
  },
  {
   "title": "Pub Key",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "solana_validator_activated_stake",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  { "title": "Validator Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Node Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "solana_node_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Node Health",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solana_node_health" }
   ]
  },
  {
   "title": "Validator Active Stake",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "solana_validator_activated_stake"
    }
   ]
  },
  {
   "title": "Commission",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "solana_val_commission" }
   ]
  },
  {
   "title": "Vote Account",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_vote_account" }
   ]
  },
  {
   "title": "IP Address",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "solana_ip_address", "legendFormat": "{{ip_address}}" }
   ]
  },
  { "title": "Validator Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Network Epoch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_network_epoch" }
   ]
  },
  {
   "title": "Validator Epoch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_confirmed_epoch_number" }
   ]
  },
  {
   "title": "Epoch Difference ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_epoch_diff" }
   ]
  },
  {
   "title": "solana current slot height",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "solana_current_slot", "legendFormat": "{{solana_current_slot}}" }
   ]
  },
  {
   "title": "Block Height - Network",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_network_block_height" }
   ]
  },
  {
   "title": "Block Height - Validator",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_block_height" }
   ]
  },
  {
   "title": "Block Height Difference",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_block_height_diff" }
   ]
  },
  {
   "title": "Voting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_val_status" }
   ]
  },
  {
   "title": "Skip Rate - Validator",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "solana_val_skip_rate" }
   ]
  },
  {
   "title": "Skip Rate - Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "solana_net_skip_rate" }
   ]
  },
  {
   "title": "Skip Rate - Difference",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "solana_skip_rate_diff" }
   ]
  },
  {
   "title": "Vote Height - Validator",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    { "expr": "solana_validator_vote_height" }
   ]
  },
  {
   "title": "Vote Height - Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    { "expr": "solana_network_vote_height" }
   ]
  },
  {
   "title": "Vote Height Difference",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    { "expr": "solana_vote_height_diff" }
   ]
  },
  { "title": "Validator Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Current Epoch - Vote Credits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "solana_vote_credits", "legendFormat": "{{solana_current_credits}}" }
   ]
  },
  {
   "title": "Previous Epoch - Vote Credits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 32 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "solana_vote_credits", "legendFormat": "{{solana_previous_credits}}" }
   ]
  },
  {
   "title": "Identity Account Balance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "account_balance" }
   ]
  },
  {
   "title": "Confirmed Block Time - Network",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 32 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "solana_network_confirmed_time",
     "legendFormat": "{{solana_network_confirmed_time}}"
    }
   ]
  },
  {
   "title": "Confirmed Block Time - Validator",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "solana_val_confirmed_time", "legendFormat": "{{solana_val_confirmed_time}}" }
   ]
  },
  {
   "title": "Confirmed Epoch Last Slot  - Validator",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "solana_confirmed_epoch_last_slot"
    }
   ]
  },
  {
   "title": "Confirmed Epoch Last Slot - Network",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "solana_network_confirmed_epoch_last_slot"
    }
   ]
  },
  {
   "title": "Vote Account Balance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_vote_account_balance", "legendFormat": "{{solana_vote_acc_bal}}" }
   ]
  },
  {
   "title": "Total Transactions Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    { "expr": "solana_tx_count", "legendFormat": "{{solana_tx_count}}" }
   ]
  },
  {
   "title": "Recent Block Production - Current Epoch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Leader Slots - Validator",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_val_leader_slots" }
   ]
  },
  {
   "title": "Total Slots - Current Epoch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_total_slots" }
   ]
  },
  {
   "title": "Blocks Produced -  Validator",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_val_blocks_produced" }
   ]
  },
  {
   "title": "Total Blocks Produced - Current Epoch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_total_blocks_produced" }
   ]
  },
  {
   "title": "Skipped Slots - Validator",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 48 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_val_skipped_slots" }
   ]
  },
  {
   "title": "Total Skipped Slots Network - Current Epoch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 48 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "solana_skipped_total" }
   ]
  },
  { "title": "Extra Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Slot Leader",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 52 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "solana_slot_leader", "legendFormat": "{{solana_slot_leader}}" }
   ]
  },
  {
   "title": "Delinquent Validators",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "solana_active_validators{state=\"delinquent\"}"
    }
   ]
  },
  {
   "title": "Current Active Validators",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "solana_active_validators{state=\"current\"}"
    }
   ]
  },
  {
   "title": "Confirmed Slot Height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    { "expr": "solana_confirmed_slot_height" }
   ]
  },
  {
   "title": "Last Voted",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    { "expr": "solana_validator_last_vote" }
   ]
  },
  {
   "title": "Validator Root Slot",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    { "expr": "solana_validator_root_slot" }
   ]
  }
 ]
}